name: Deploy Frontend to OSS

on:
  push:
    branches: [ main ] # main分支变动时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24' # 你的前端node版本
          
      - name: Build Frontend
        run: |
          npm install
          npm run build # 打包出 dist 目录
          
      - name: Setup Aliyun OSS CLI
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          # 替换为你的 OSS 所在地域 Endpoint，例如 oss-cn-hangzhou.aliyuncs.com
          endpoint: oss-cn-beijing.aliyuncs.com
          # 记得在 GitHub 前端仓库的 Secrets 中配置这两个变量
          access-key-id: ${{ secrets.ALIOSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIOSS_ACCESS_KEY_SECRET }}
          
      - name: Upload to OSS
        # 将 dist 目录下的所有文件强制覆盖上传到 Bucket 根目录
        # 记得把 <your-bucket-name> 换成你真实的 bucket 名字
        run: ossutil cp -rf dist/ oss://<linkcode>/